imports:
    - { resource: 'services/handlers.yml' }
services:
      kodify_blog.form.data_transformer.post_to_number:
          class: Kodify\BlogBundle\Form\DataTransformer\PostToNumberTransformer
          arguments: ["@doctrine.orm.entity_manager"]
