services:
#    kodify_blog.example:
#        class: Kodify\BlogBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    kodify_blog.sort:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - "KodifyBlogBundle:Post"

