default:
    suites:
        default:
            type: symfony_bundle
            bundle: 'KodifyBlogBundle'
    extensions:
        Behat\Symfony2Extension:
            kernel:
                env: test
                debug: true
        Behat\MinkExtension:
            base_url: 'http://blog/app_test.php'
            browser_name: firefox
            sessions:
                default:
                    symfony2: ~
                javascript:
                    selenium2: ~
            show_cmd: open -a Google\ Chrome %s