security:
    encoders: 
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        in_memory:
            memory:
                users:
                    someone: { password: 123456, roles: 'ROLE_USER' }
                    over: { password: 123456, roles: 'ROLE_USER' }
                    rainbow: { password: 123456, roles: 'ROLE_USER' }
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            pattern: ^/ # everything will go through this firewall
            form_login:
                login_path:  login # the route name for your login route
                check_path:  login_check # the rout name for your login check route
            logout:
                path: /logout
                target: /
            anonymous: true 


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }

