<?php

namespace Kodify\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class AbstractBaseRepository extends EntityRepository
{
    /**
     * Gets the latest entries
     *
     * @param int $limit Number of entries to retrieve
     * @param int $offset Number of ordered entries to skip
     * @return array
     */
    public function latest($limit, $offset = 0)
    {
        return $this->findBy([], ['createdAt' => 'DESC'], $limit, $offset);
    }


}
