<?php

namespace Kodify\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class AbstractBaseRepository extends EntityRepository
{
    const LIST_DEFAULT_LIMIT = 5;

    public function latest($limit = null, $offset = 0)
    {
        $limit = $this->getLimit($limit);

        return $this->findBy([], ['createdAt' => 'DESC'], $limit, $offset);
    }

    /**
     * @param $limit
     *
     * @return int
     */
    protected function getLimit($limit)
    {
        if (is_null($limit)) {
            return static::LIST_DEFAULT_LIMIT;
        }

        return $limit;
    }
}
