<?php

namespace Kodify\BlogBundle\Repository;
use Kodify\BlogBundle\Entity\Author;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends AbstractBaseRepository
{
    /**
     * Persists the given author to the database
     * @param $author Author
     */
    public function persist($author)
    {
        $this->getEntityManager()->persist($author);
        $this->getEntityManager()->flush();
    }
}
