<?php

namespace Kodify\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Kodify\BlogBundle\Domain\AuthorInterface;
use Kodify\BlogBundle\Domain\AuthorRepositoryInterface;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends EntityRepository implements AuthorRepositoryInterface
{
    /**
     * {@inheritdoc}
     * @param AuthorInterface $author
     */
    public function persist($author)
    {
        $this->getEntityManager()->persist($author);
        $this->getEntityManager()->flush();
    }

    /**
     * {@inheritdoc}
     */
    public function latest($limit, $offset = 0)
    {
        return $this->findBy([], ['createdAt' => 'DESC'], $limit, $offset);
    }
}
