<?php

namespace Kodify\BlogBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends AbstractBaseRepository
{
	const LIST_DEFAULT_LIMIT = 5;
	
	public function getCommentsForPost($postId)
    {
        $query = $this->createQueryBuilder('c')
                   ->select('c')
                   ->where('c.post = :postId')
                   ->addOrderBy('c.createdAt')
                   ->setParameter('postId', $postId);

        return $query->getQuery()->getResult();
    }
}
