<?php

namespace Kodify\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends AbstractBaseRepository
{
	public function getPostComments($postId)
    {
        $builder = $this->createQueryBuilder('c')
                   ->select('c')
                   ->where('c.postId = :post_id')
                   ->addOrderBy('c.createdAt')
                   ->setParameter('post_id', $postId);

        return $builder->getQuery()->getResult();
    }
}
