<?php

namespace Kodify\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Kodify\BlogBundle\Domain\CommentRepositoryInterface;
use Kodify\BlogBundle\Domain\CommentInterface;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository implements CommentRepositoryInterface
{
    /**
     * {@inheritdoc}
     * @param CommentInterface $comment
     */
    public function persist($comment)
    {
        //TODO:: Persist it
        /*
        $this->getEntityManager()->persist($comment);
        $this->getEntityManager()->flush();
        */
    }

    /**
     * {@inheritdoc}
     */
    public function getLatestByPost($post, $limit, $offset = 0)
    {
        return $this->findBy(['post' => $post],
            ['createdAt' => 'DESC'],
            $limit,
            $offset);
    }
}
