<?php

namespace Kodify\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Kodify\BlogBundle\Domain\PostInterface;
use Kodify\BlogBundle\Domain\PostRepositoryInterface;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository implements PostRepositoryInterface
{
    /**
     * {@inheritdoc}
     * @param PostInterface $post
     */
    public function persist($post)
    {
        $this->getEntityManager()->persist($post);
        $this->getEntityManager()->flush();
    }

    /**
     * {@inheritdoc}
     */
    public function latest($limit, $offset = 0)
    {
        return $this->findBy([], ['createdAt' => 'DESC'], $limit, $offset);
    }
}
