<?php

namespace Kodify\BlogBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends AbstractBaseRepository
{
    public function latestOrdered($fieldToOrderBy = null, $limit = null, $offset = 0)
    {
        $validOrderByFields = ['rating'];
        if (!in_array($fieldToOrderBy, $validOrderByFields)) {
            $fieldToOrderBy = 'p.createdAt';
        }

        if (is_null($limit)) {
            $limit = static::LIST_DEFAULT_LIMIT;
        }

        return $this->createQueryBuilder('p')
            ->select('p')
            ->addSelect('SUM(r.value)/COUNT(r.id) AS HIDDEN rating')
            ->leftJoin('p.ratings', 'r', 'r.postId = p.id')
            ->groupBy('p')
            ->orderBy($fieldToOrderBy, 'DESC')
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();

        return $this->findBy([], [$fieldToOrderBy, 'DESC'], $limit, $offset);
    }
}
