<?php

namespace Kodify\BlogBundle\Repository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends AbstractBaseRepository
{
	public function getRatingsForPost($postId)
	{
		$query = $this->createQueryBuilder('r')
		->select('r')
		->where('r.post = :postId')
		->setParameter('postId', $postId);
	
		return $query->getQuery()->getResult();
	}
	
	public function checkIfUserHasRateIt($postId, $author)
	{
		$query = $this->createQueryBuilder('r')
		->select('r')
		->where('r.post = :postId')
		->andWhere('r.author = :authorId')
		->setParameter('postId', $postId)
		->setParameter('authorId', $author->getId());
		$result = $query->getQuery()->getResult();
		if(empty($result)){
			return FALSE;
		} else {
			return TRUE;
		}
	}
}
